### ISSUE TITLE
broken link to wiki guide with set up of environment variables

### ISSUE THREAD

**Issue by baranovRP** [jtalks-org/functional-tests#69]
broken link from https://github.com/jtalks-org/functional-tests to wiki guide with set up of environment variables
![image](https://cloud.githubusercontent.com/assets/2158131/8860224/bb6a6c8c-3182-11e5-88c6-36e6b215f671.png)

**Comment by ctapobep** [comment]
I removed the link completely, people should use the tools' installation guides instead of our custom one.

But the link was pointing to: http://wiki.jtalks.org/display/env/Environment+Home+Page
